Rails associations in a working MVC application
gabrie-lhilarion/private-events pull request #2
Opened 2020-11-05 14:42 UTC by gabrie-lhilarion

# Implemented a working MVC application
- Created model, views, and controllers
- Developed a custom and yet very functional authentication (login and account creation system)
- Added some nice user interface using bootstrap

2020-11-05 16:48 UTC, lekegitrepo requested changes
## Status: Request changes :recycle:
#### Hi @gabrie-lhilarion :clap: :clap:
#### You have done a good :+1: However, some requirements are missing/not properly implemented. Check my comments below.

#### Tests

* [ ] **_Models should have unit tests for validations and associations (Rspec) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/unit_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))_**

* [ ] **_authentication should have integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))_**

* [ ] **_Event managment features should have integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))_**

#### Error!
- **_When I tried to create an account this error was displayed after clicking the "create account" button_**
![Screenshot from 2020-11-05 10-13-09](https://user-images.githubusercontent.com/48312803/98266503-0237fb00-1f50-11eb-9e67-e6a7bb5f520e.png)

#### App Functionality
- **_The user's show page should contain events that the user is attending separated in past and upcoming **(covered by automated tests)** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))_**

#### _Reviewed by Temitayo Adeleke_

2020-11-05 16:48 UTC, lekegitrepo commented on config/routes.rb
> +resources :events
- **_routes only for used actions, for example: `resources :events, only: [:new, :create, :show, :index]`_**

2020-11-12 18:14 UTC, gabrie-lhilarion commented
## WORKED ON REQUIRED CHANGES
- Created test for  model relationships
- Created integration test, for user interactions using Rspec and Capybara

2020-11-12 19:13 UTC, blackpintz requested changes
# Status: Changes Required

## Hello team,

**Great job implementing the changes. However, there are a few fixes needed.**

1). **The application shows the error below when I try to view any of the routes.**

![route-err](https://user-images.githubusercontent.com/38922385/98982089-df00e300-252f-11eb-845c-892b443e93c1.png).

2). **Please check more in the comments below.**

### Happy coding 😃.

**PS: You can reach me on slack (Rose Wanjohi).**

2020-11-12 19:13 UTC, blackpintz commented on app/models/invitation.rb
> +end
Write unit tests for the `model/invitation.rb`.` The invitation_spec.rb` is empty.

2020-11-12 19:13 UTC, blackpintz commented on app/models/user.rb
> +end
Write unit tests for the `model/user.rb`. The ` user_spec.rb` is empty.

2020-11-12 19:13 UTC, blackpintz commented on spec/features/login_user_spec.rb
> +end
This test is failing.

2020-11-12 19:13 UTC, blackpintz commented on spec/features/create_user_spec.rb
> +end
This test is failing.

2020-11-12 19:13 UTC, blackpintz commented on spec/requests/events_request_spec.rb
> +end
Add tests here.

2020-11-12 19:13 UTC, blackpintz commented on spec/requests/sessions_request_spec.rb
> +end
Add tests here.

2020-11-12 19:13 UTC, blackpintz commented on spec/requests/users_request_spec.rb
> +end
Add tests here.

2020-11-14 13:17 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

### Excellent Job Team 👏  

You've done an awesome job so far 👌. But there are still some changes that are necessary for this project to be approved.

It looks like you broke some things while fixing previous errors.

- [ ] I get an error when I click **See all Events** 
<img width="1000" alt="Screen Shot 2020-11-14 at 1 38 00 PM" src="https://user-images.githubusercontent.com/5264771/99147169-00bcb000-267f-11eb-9b00-d38d3f85ec5f.png">

- [ ] When trying to create an event, it throws an error: 
<img width="1030" alt="Screen Shot 2020-11-14 at 1 52 15 PM" src="https://user-images.githubusercontent.com/5264771/99147365-ba685080-2680-11eb-8bf5-7dd248e5d2ec.png">

### use `rails routes` to be certain of the routes you are using in your view.


- [ ] Clicking on Edit button for users throws an error: _The action 'edit' could not be found for UsersController_

- [ ] There should be absolutely NO logic in views. >Views are only for displaying information that becomes available to it from its corresponding controller not generating it. **Resources**
* [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
* [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
*[Rails view helpers best practices guide](https://medium.com/@acushla4real/rails-view-helpers-best-practices-guide-d7d7b6db3db4)
* [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright View-related logic can be encapsulated in View helpers (app/helpers/*_helper.rb)

- [ ] [OPTIONAL] When a user clicks on `Attend this event`, it should change the text to something like `Attending`. And if the user clicks a second time, update the text to suit the case. 'You're already an attendee' or something instead of 'You are already a member. You can only register once!' This is purely optional.

- [ ] Since Testing has been included, update your readme file to show how to run tests on your application.

- [ ] Your tests are failing, kindly fix it.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2020-11-18 16:02 UTC, mcrd25 approved these changes
# Changes Approved :heavy_check_mark: 

Hi @gabrie-lhilarion :wave: 

Good job, 

You addressed all points of lass review, so there is no need for further review.
However, please consider my optional comments:

### Recommendations
- Maybe the Welcome label on the navbar should not be a button, a button represents completing an action which that does not do. ![Screenshot from 2020-11-18 10-29-06](https://user-images.githubusercontent.com/31193823/99555572-d4fb3c00-2996-11eb-926d-e74ef7f7f1db.png)

- As was mentioned before, it is not user-friendly to have the text say attend this event after the user has already attended the event. Consider removing it or replacing it with some kind of unattended functionality when the user has already clicked attended an event. 
![Screenshot from 2020-11-18 10-29-12](https://user-images.githubusercontent.com/31193823/99555610-dd537700-2996-11eb-8c0a-bc706a7a7423.png)


Hope this review was helpful, and congratulations! :partying_face: 

***If you have any questions, now or in the future, do not hesitate to contact me on social media, email or on slack and I will be glad to chat with you.***

*Happy coding 😄,*
**[--Maya Douglas](mayacdouglas.com)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

2020-11-19 06:03 UTC, merged